<?php
/**
 * @var \RockLab\Gifto\Block\GifNote $block
 */

$productId = $block->getData('viewModel')->getProductId();
//$giftId = $block->getGiftId($productId);
$arrayProd = $block->getGiftCollectionItems($productId);
    if (!empty($arrayProd)):
?>
<div>
    <p>If you buy <?= $arrayProd['qty'];?> you will receive bonus products
    <?= $arrayProd['bonusProducts']; ?>
    </p>
</div>
<?php endif;?>
